language: Java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "marcio012"
    token:
      secure: f72ea3cf07b27aeb8c532e0ffb6cf475fcf3d7f0 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
